image: node

before_script:
  - yarn install

stages:
  - unit-test
  - build

build-node:
  stage: build
  script:
    - yarn build

test-helper:
  stage: unit-test
  before_script:
  script:
    - yarn test
